### ISSUE TITLE
Can you publish your code?

### ISSUE THREAD

**Issue by sashatytko** [IvanKor/hrfGPS#2]
Hi.I want to use your project.How I can get it?

**Comment by IvanKor** [comment]
это не детский проект

**Comment by sashatytko** [comment]
Ну и что

**Comment by IvanKor** [comment]
а ничего .... посмотрели картинки и спать ...

**Comment by sashatytko** [comment]
Зачем делать проект на гитхабе и выставлять картинки.Я серьезно занимаюсь проектом и уже запускал sdr gps sim.Также занимаюсь gsm изучениям(osmocombb,airprobe)

**Comment by sashatytko** [comment]
Интерисует сам процес как создать так что бы  можно было делать подмену в реальном времени.Как с Вами можно связаться?

**Comment by IvanKor** [comment]
никак, сказал уже, это не детский проект, это проект РЭБ
