### ISSUE TITLE
Time sync

### ISSUE THREAD

**Issue by Eduardo-F** [IvanKor/hrfGPS#5]
Hi, I would like to know if the SDR device feed by hrfGPS emits a GPS signal synchronized with time of the host PC on which it running. 
I mean, time received by a GPS receiver and time on the host PC will be the same?  Is there any offset? 

Thank you

**Comment by IvanKor** [comment]
hackrf has an external generator that is synchronized with GPS (PPS)

**Comment by Eduardo-F** [comment]
thank you.
Could you contact me?
efernandezortiz@hotmail.com

**Comment by ferorted** [comment]
Can i contact you for a possible collaboration?

**Comment by IvanKor** [comment]
> 
> Can i contact you for a possible collaboration?

ivan1955_2017@i.ua
